### ISSUE TITLE
URL da revisionare

### ISSUE THREAD

**Issue by aborruso** [italia/linee-guida-cataloghi-dati-dcat-ap-it#10]
Buongiorno,
gli URL degli RDF di questo elenco sembrano da aggiornare: https://github.com/italia/linee-guida-cataloghi-dati-dcat-ap-it/blob/d0f258ae681d5310381c582b6a21b2eacafe3db1/src/voccontrollati.rst

Saluti e grazie

**Comment by giorgialodi** [comment]
Ciao @aborruso grazie! In effetti la commissione ha cambiato un po' tutto sui vocabolari ed è bene aggiornarli. Metterei però, invece che l'RDF la pagina dove si trovano tutti i formati di distribuzione del vocabolario e la tabella di navigazione html.

**Comment by giorgialodi** [comment]
@aborruso link aggiornati. Grazie!

**Comment by aborruso** [comment]
A voi
